### ISSUE TITLE
Terrible project

### ISSUE THREAD

**Issue by AImissq** [demian-wolf/antioverheat-gui#2]
This is the worst dev job I've seen in a while. Why bother wasting peoples time?

**Comment by demian-wolf** [comment]
I know it's terrible, lmao.

It used to do the job for me, though.
I could achieve slightly higher performance with a bit less overheating.
The overheating notification was also quite helpful.

I don't remember I insisted on anyone using this project.

Looks like you're trying really hard to waste **my** time on reading issues without any specific or meaningful information.
